spring:
  datasource:
    username: aerie
    password: <<HIDDEN>>
  cloud:
    gcp:
      sql:
        database-name: aerie_test
        instance-connection-name: aerie-sa:us-east1:aerie
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  FETCH_DATA=false
  UPDATE_DATA=false
  ROSTER_USER=user
  ROSTER_PASS=pass
  DB_URL=jdbc:mysql://localhost:3306/members
  DB_USER=user
  DB_PASS=pass
