#
#  Copyright (C) 2021 Gwinnett County Experimental Aircraft Association
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

aerie:
  weather:
    atlanta-icao-codes: KCNI,KGVL,KVPC,KJCA,KRYY,KLZU,KWDR,KPUJ,KMGE,KPDK,KFTY,KCTJ,KCVC,KATL,KCCO,KFFC,KHMP,KLGC,KOPN
  roster:
    username: <<username>>
    password: <<password>>
  jotform:
    api-key: <<api-key>>
    new-member-form-id: <<form-id>>
    member-renewal-form-id: <<form-id>>
    base-url: https://form.jotform.com/
  tinyurl:
    api-key: <<api-key>>
    create-url: https://api.tinyurl.com/create
  email:
    host: mail.eaa690.org
    smtp-port: 587
    letterhead: /Users/bmichael/aerie/images/eaa690_letterhead.png
    template-path: /Users/bmichael/aerie/templates/
  membership:
    host: http://aerie.eaa690.org
    username: <<username>>
    password: <<password>>
    new-subject: Welcome to EAA 690
    renew-subject: EAA 690 Membership Renewal
  slack:
    token: <<token>>
    base-url: https://slack.com/api/
    template-path: /Users/bmichael/aerie/templates/
  tracking:
    host: http://aerie.eaa690.org
  groundschool:
    secret-key: <<secret-key>>
    init-vector: <<init-vector>>
    db-location: /Users/bmichael/aerie/gs
  timed-tasks:
    tasks:
      update-weather: 0 0,10,20,30,40,50 * * * ?
      update-roster: 0 0 0,6,12,18 * * ?
      update-questions-and-answers: 0 0 6 1,10,20 * ?
      get-jot-form-submissions: 0 0 * * * ?
      send-membership-renewal-messages: 0 0 9 1,10,20 * ?
      clean-job-status-repo: 0 0 5 * * ?

http:
  port: 8081

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/aerie.p12
    key-store-password: <<password>>
    key-alias: aerie
  port: 8443

spring:
  h2:
    console:
      enabled: true
  datasource:
    username: <<username>>
    password: <<password>>
    url: jdbc:h2:mem:aerie
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
          scheduler:
            instanceId: AUTO
  thymeleaf:
    template-loader-path: classpath:/templates