#
#  Copyright (C) 2021 Gwinnett County Experimental Aircraft Association
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

aerie:
  weather:
    atlanta-icao-codes: KCNI,KGVL,KVPC,KJCA,KRYY,KLZU,KWDR,KPUJ,KMGE,KPDK,KFTY,KCTJ,KCVC,KATL,KCCO,KFFC,KHMP,KLGC,KOPN
  roster:
    username: <<username>>
    password: <<password>>
  jotform:
    api-key: <<api-key>>
    new-member-form-id: <<form-id>>
    member-renewal-form-id: <<form-id>>
    base-url: https://form.jotform.com/
  mailchimp:
    api-key: <<api-key>>
    members-list-id: <<list-id>>
    non-members-list-id: <<list-id>>
  tinyurl:
    api-key: <<api-key>>
    create-url: https://api.tinyurl.com/create
  membership:
    username: <<username>>
    password: <<password>>
    letterhead: <<path>>eaa690_letterhead.png
    subject: EAA 690 Membership Renewal
    body: <p>Hello {{firstName}} {{lastName}}</p><p>The time has come to renew your membership.  Your membership is set to expire on {{expirationDate}}.  Be sure to go to <a href="{{url}}">https://eaa690.org</a> soon to make sure you remain in good standing.</p><p>A few reasons to keep your membership current:</p><ul><li>Access to the chapter hangar at LZU</li><li>Receive our monthly newsletter</li><li>Help us educate, inspire, and share aviation with the local community</li></ul>

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:aerie
  data:
    jpa:
      repositories:
        bootstrap-mode: default
