spring:
  datasource:
    username: aerie
    password: ${AERIE_DB_PASS}
    url: jdbc:mysql://localhost:3306/aerie?serverTimezone=America/New_York
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
